--De chay view 6
INSERT ALL
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES ('C:\BA\Year 2 Semester 2\8 Thiet ke CSDL\Bai tap lon\Elements\Pictures\Avatar\Pexel.jpeg', 'Hung Phuc1', '123456', 'hungtran1@gmail.com', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 'VN', 'Admin')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES ('C:\BA\Year 2 Semester 2\8 Thiet ke CSDL\Bai tap lon\Elements\Pictures\Avatar\Duong.jpg', 'Nguyen Duong1', 'password123', 'duongnguyen1@hotmail.com', TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'SG', 'Admin')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES ('C:\BA\Year 2 Semester 2\8 Thiet ke CSDL\Bai tap lon\Elements\Pictures\Avatar\SadGuy.jpg', 'Thien Phu1', 'abc123', 'aphudeptrai1@yahoo.com', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 'JP', 'Admin')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES ('C:\BA\Year 2 Semester 2\8 Thiet ke CSDL\Bai tap lon\Elements\Pictures\Avatar\Kids.jpg', 'Bui Quoc1', 'def456', 'tlaquoc1@outlook.com', TO_DATE('2023-12-25', 'YYYY-MM-DD'), 'KR', 'Admin')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES ('C:\BA\Year 2 Semester 2\8 Thiet ke CSDL\Bai tap lon\Elements\Pictures\Avatar\Viet.jpeg', 'Vu Viet1', 'ghi789', 'vietdeptrai1@icloud.com', TO_DATE('2024-03-08', 'YYYY-MM-DD'), 'CN', 'Admin')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'hoangnguyen1', '123456', 'hoangnguyen1@gmail.com', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 'VN', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'minhphuong1', 'password123', 'minhphuong1@hotmail.com', TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'SG', 'Moderator')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'thuylinh1', 'abc123', 'thuylinh1@yahoo.com', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 'JP', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'vannam1', 'def456', 'vannam1@outlook.com', TO_DATE('2023-12-25', 'YYYY-MM-DD'), 'KR', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'kimngan1', 'ghi789', 'kimngan1@icloud.com', TO_DATE('2024-03-08', 'YYYY-MM-DD'), 'CN', 'Moderator')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Linh Chi1', 'jkl123', 'linhchi1@outlook.com', TO_DATE('2024-04-20', 'YYYY-MM-DD'), 'US', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Nam Son1', 'mno456', 'namson1@gmail.com', TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'AU', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Mai Anh1', 'pqr789', 'maianh1@hotmail.com', TO_DATE('2023-10-27', 'YYYY-MM-DD'), 'FR', 'Moderator')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Quang Minh1', 'stu000', 'quangminh1@icloud.com', TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'DE', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Ha My1', 'uvw987', 'hamy1@yahoo.com', TO_DATE('2023-09-01', 'YYYY-MM-DD'), 'GB', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Lan Anh1', 'jkl123', 'lananh1@gmail.com', TO_DATE('2024-04-12', 'YYYY-MM-DD'), 'US', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Duc Minh1', 'mno456', 'ducminh1@hotmail.com', TO_DATE('2024-03-01', 'YYYY-MM-DD'), 'CA', 'Moderator')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Ngoc Lien1', 'pqr789', 'ngoclien1@outlook.com', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 'AU', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Phuong Vy1', 'stu000', 'phuongvy1@icloud.com', TO_DATE('2023-11-17', 'YYYY-MM-DD'), 'NZ', 'User')
    INTO TaiKhoan (AnhDaiDien, TenTaiKhoan, MatKhau, Email, NgayThamGia, QuocGia, ChucVu) 
    VALUES (NULL, 'Minh Tri1', 'uvw987', 'minhtri1@yahoo.com', TO_DATE('2023-08-25', 'YYYY-MM-DD'), 'SG', 'User')
SELECT * FROM dual;

